### ISSUE TITLE
Using eNetXplorer to elastic net models built by sklearn

### ISSUE THREAD

**Issue by fullcream9** [juliancandia/eNetXplorer#2]
Hi everyone,

Can I use eNetXplorer to interpret elastic net models built by sklearn in python? If so,  how to do?

Any help is greatly appreciated!

**Comment by juliancandia** [comment]
Hi Panshi, 
eNetXplorer runs in R. The best advice I can give is that, once you identify a useful elastic net model via Scikit-learn, you could re-run it via eNetXplorer in R to benefit from the added interpretation that it provides. Hope this addresses your concern.
